-- Create the contact_messages table to store contact form submissions
create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    email text not null,
    organization text,
    message text not null
);

-- Enable Row Level Security (RLS) on the table
alter table public.contact_messages enable row level security;

-- Create policy to allow anyone to insert messages (needed for public contact form)
create policy "Allow public inserts" 
on public.contact_messages 
for insert 
with check (true);

-- Optional: Create policy to allow authenticated users (like an admin) to view submissions
create policy "Allow authenticated selects" 
on public.contact_messages 
for select 
to authenticated 
using (true);
